services:
  cloud-router:
    image: ubuntu:22.04
    container_name: cloud-router
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    networks:
      net-fabric:
        ipv4_address: 192.168.56.10

  telco-router:
    image: ubuntu:22.04
    container_name: telco-router
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - SYS_ADMIN
    networks:
      net-fabric:
        ipv4_address: 192.168.56.20

networks:
  net-fabric:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
