version: '3.8'

services:
  cloud-router:
    image: frrouting/frr:latest
    container_name: cloud-router
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/router_bgp.conf:/etc/frr/frr.conf
      - ./configs/vpn:/etc/ipsec.d
    networks:
      net-mgmt:
        ipv4_address: 192.168.56.10

  telco-router:
    image: frrouting/frr:latest
    container_name: telco-router
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/telco_bgp.conf:/etc/frr/frr.conf
      - ./configs/vpn:/etc/ipsec.d
    networks:
      net-mgmt:
        ipv4_address: 192.168.56.20

networks:
  net-mgmt:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
