config setup
    uniqueids = yes

conn %default
    keyingtries = %forever
    ikelifetime = 60m
    keylife = 20m
    rekeymargin = 3m
    keyexchange = ikev2
    authby = secret

conn net-to-net
    left = 192.168.56.10
    leftsubnet = 10.0.0.0/16
    right = 192.168.56.20
    rightsubnet = 10.1.0.0/16
    auto = start
