!
route-map ALLOW-ALL permit 10
!
router bgp 65001
 bgp router-id 192.168.56.10
 neighbor 192.168.56.20 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.0.0.1/32
  neighbor 192.168.56.20 activate
  neighbor 192.168.56.20 soft-reconfiguration inbound
  neighbor 192.168.56.20 route-map ALLOW-ALL in
  neighbor 192.168.56.20 route-map ALLOW-ALL out
 exit-address-family
!
line vty
!
