!
router bgp 65001
 bgp router-id 192.168.56.10
 neighbor 192.168.56.20 remote-as 65002
 !
 address-family ipv4 unicast
  network 10.0.0.0/16
  neighbor 192.168.56.20 activate
 exit-address-family
!
line vty
!
