!
route-map ALLOW-ALL permit 10
!
router bgp 65002
 bgp router-id 192.168.56.20
 neighbor 192.168.56.10 remote-as 65001
 !
 address-family ipv4 unicast
  network 10.1.0.1/32
  neighbor 192.168.56.10 activate
  neighbor 192.168.56.10 soft-reconfiguration inbound
  neighbor 192.168.56.10 route-map ALLOW-ALL in
  neighbor 192.168.56.10 route-map ALLOW-ALL out
 exit-address-family
!
line vty
!
